// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbud0s6ocEuI_EhjWO920lqCoBguIFfHY',
    appId: '1:580576712272:web:1acc85a7e56c98ff4c6355',
    messagingSenderId: '580576712272',
    projectId: 'link-note-app',
    authDomain: 'link-note-app.firebaseapp.com',
    storageBucket: 'link-note-app.appspot.com',
    measurementId: 'G-6ZDPM21GLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD49tozP8yVdakmzromyWEard72H5FduSk',
    appId: '1:580576712272:android:059ce36e77a8d6664c6355',
    messagingSenderId: '580576712272',
    projectId: 'link-note-app',
    storageBucket: 'link-note-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGXywG2R-02DBzzLZbetigIrI6g3PnOTY',
    appId: '1:580576712272:ios:f93ae13f975cfce24c6355',
    messagingSenderId: '580576712272',
    projectId: 'link-note-app',
    storageBucket: 'link-note-app.appspot.com',
    iosClientId:
        '580576712272-968njh1qn6jf2vkp6hu18hif6g1csc66.apps.googleusercontent.com',
    iosBundleId: 'app.link-note.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGXywG2R-02DBzzLZbetigIrI6g3PnOTY',
    appId: '1:580576712272:ios:f93ae13f975cfce24c6355',
    messagingSenderId: '580576712272',
    projectId: 'link-note-app',
    storageBucket: 'link-note-app.appspot.com',
    iosClientId:
        '580576712272-968njh1qn6jf2vkp6hu18hif6g1csc66.apps.googleusercontent.com',
    iosBundleId: 'app.link-note.notes',
  );
}
